### ISSUE TITLE
when i sort the list that's crash on Android.

### ISSUE THREAD

**Issue by maxing19920124** [gitim/react-native-sortable-list#10] opened 2017-02-06 03:28 UTC
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by hungdev** [comment] 2017-02-06 04:04
i have same error. it discuss here https://github.com/gitim/react-native-sortable-list/issues/2

**Comment by joshuapinter** [comment] 2017-03-05 16:58
Duplicate of #2. Suggest closing.

**Comment by joshuapinter** [comment] 2017-03-06 03:14
See my issue and resulting PRs over at #15.

**Comment by gitim** [comment] 2017-03-06 21:37
works in master, will release a version very soon

**Closed by gitim** 2017-03-06 21:37 UTC
